In [7]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/Mozun1/task2/main/loans_open_date_2022_06.csv")

In [20]:
df.head()

,المدينة,التصنيف,االمنتج,قطاع_العميل,مبلغ_التمويل,قيمة_القسط,تاريخ_الصرف,جنس_العميل,عمر_العميل,ألحاله_الإجتماعية,إحتياجات_خاصة,عدد_أفراد_الأسره,زود_الإدخاري,القيمة
0,بنك التنمية الإجتماعية بالإحساء,نقل,قرض سيارة أجرة,قطاع خاص,78334.0,>= 1000,2022-06,ذكر,>= 40,متزوج,سليم,غير معروف,0,0
1,بنك التنمية الإجتماعية فرع المجمعة,مشروع,قرض التميز,قطاع خاص,2877000.0,>= 1000,2022-03,انثى,>= 30,متزوج,سليم,< 02,0,0
2,بنك التنمية الإجتماعية فرع الرياض,مشروع,قرض مشروع حل,قطاع خاص,281000.0,>= 1000,2022-03,انثى,>= 30,متزوج,سليم,< 02,0,0
3,بنك التنمية الإجتماعية فرع الرياض,مشروع,قرض التميز,قطاع خاص,1700000.0,>= 1000,2022-04,ذكر,>= 40,متزوج,سليم,< 02,0,0
4,بنك التنمية الإجتماعية فرع جدة,مشروع,قرض التميز,قطاع خاص,2218980.0,>= 1000,2022-01,ذكر,>= 30,متزوج,سليم,< 02,0,0

In [ ]:
import pandas as pd

df = pd.read_xml("https://raw.githubusercontent.com/Mozun1/task2/main/loans_open_date_2022_06.xml")

In [22]:
df.head()

,المدينة,التصنيف,االمنتج,قطاع_العميل,مبلغ_التمويل,قيمة_القسط,تاريخ_الصرف,جنس_العميل,عمر_العميل,ألحاله_الإجتماعية,إحتياجات_خاصة,عدد_أفراد_الأسره,زود_الإدخاري,القيمة
0,بنك التنمية الإجتماعية بالإحساء,نقل,قرض سيارة أجرة,قطاع خاص,78334.0,>= 1000,2022-06,ذكر,>= 40,متزوج,سليم,غير معروف,0,0
1,بنك التنمية الإجتماعية فرع المجمعة,مشروع,قرض التميز,قطاع خاص,2877000.0,>= 1000,2022-03,انثى,>= 30,متزوج,سليم,< 02,0,0
2,بنك التنمية الإجتماعية فرع الرياض,مشروع,قرض مشروع حل,قطاع خاص,281000.0,>= 1000,2022-03,انثى,>= 30,متزوج,سليم,< 02,0,0
3,بنك التنمية الإجتماعية فرع الرياض,مشروع,قرض التميز,قطاع خاص,1700000.0,>= 1000,2022-04,ذكر,>= 40,متزوج,سليم,< 02,0,0
4,بنك التنمية الإجتماعية فرع جدة,مشروع,قرض التميز,قطاع خاص,2218980.0,>= 1000,2022-01,ذكر,>= 30,متزوج,سليم,< 02,0,0

In [23]:
import pandas as pd

df = pd.read_xlsx("loans_open_date_2022_06")

In [25]:
df.head()

,المدينة,التصنيف,االمنتج,قطاع_العميل,مبلغ_التمويل,قيمة_القسط,تاريخ_الصرف,جنس_العميل,عمر_العميل,ألحاله_الإجتماعية,إحتياجات_خاصة,عدد_أفراد_الأسره,زود_الإدخاري,القيمة
0,بنك التنمية الإجتماعية بالإحساء,نقل,قرض سيارة أجرة,قطاع خاص,78334.0,>= 1000,2022-06,ذكر,>= 40,متزوج,سليم,غير معروف,0,0
1,بنك التنمية الإجتماعية فرع المجمعة,مشروع,قرض التميز,قطاع خاص,2877000.0,>= 1000,2022-03,انثى,>= 30,متزوج,سليم,< 02,0,0
2,بنك التنمية الإجتماعية فرع الرياض,مشروع,قرض مشروع حل,قطاع خاص,281000.0,>= 1000,2022-03,انثى,>= 30,متزوج,سليم,< 02,0,0
3,بنك التنمية الإجتماعية فرع الرياض,مشروع,قرض التميز,قطاع خاص,1700000.0,>= 1000,2022-04,ذكر,>= 40,متزوج,سليم,< 02,0,0
4,بنك التنمية الإجتماعية فرع جدة,مشروع,قرض التميز,قطاع خاص,2218980.0,>= 1000,2022-01,ذكر,>= 30,متزوج,سليم,< 02,0,0