In [2]:
#Currect working directory
import os
os.getcwd()

'C:\\Users\\Artist Areej'

In [8]:
import pandas as pd

In [18]:
#load the Exel file which has extension of .xlsx
data = pd.read_excel("loans_open_date_2022_06 (1).xlsx")

In [12]:
data.head()

,المدينة,التصنيف,االمنتج,قطاع_العميل,مبلغ_التمويل,قيمة_القسط,تاريخ_الصرف,جنس_العميل,عمر_العميل,ألحاله_الإجتماعية,إحتياجات_خاصة,عدد_أفراد_الأسره,زود_الإدخاري,القيمة
0,بنك التنمية الإجتماعية بالإحساء,نقل,قرض سيارة أجرة,قطاع خاص,78334.0,>= 1000,2022-06,ذكر,>= 40,متزوج,سليم,غير معروف,0.0,0.0
1,بنك التنمية الإجتماعية فرع المجمعة,مشروع,قرض التميز,قطاع خاص,2877000.0,>= 1000,2022-03,انثى,>= 30,متزوج,سليم,< 02,0.0,0.0
2,بنك التنمية الإجتماعية فرع الرياض,مشروع,قرض مشروع حل,قطاع خاص,281000.0,>= 1000,2022-03,انثى,>= 30,متزوج,سليم,< 02,0.0,0.0
3,بنك التنمية الإجتماعية فرع الرياض,مشروع,قرض التميز,قطاع خاص,1700000.0,NaN,2022-04,ذكر,>= 40,متزوج,سليم,< 02,0.0,0.0
4,بنك التنمية الإجتماعية فرع جدة,مشروع,قرض التميز,قطاع خاص,2218980.0,>= 1000,2022-01,ذكر,>= 30,متزوج,سليم,< 02,0.0,0.0

In [22]:
data.tail()

,المدينة,التصنيف,االمنتج,قطاع_العميل,مبلغ_التمويل,قيمة_القسط,تاريخ_الصرف,جنس_العميل,عمر_العميل,ألحاله_الإجتماعية,إحتياجات_خاصة,عدد_أفراد_الأسره,زود_الإدخاري,القيمة
82191,بنك التنمية الإجتماعية فرع حفر الباطن,إجتماعي,قرض زواج,قطاع خاص,42000.0,< 1000,2022-06,ذكر,< 30,متزوج,نعم,>= 02,0,0
82192,بنك التنمية الإجتماعية فرع نجران,إجتماعي,قرض أسرة,قطاع حكومي,60000.0,>= 1000,2022-06,ذكر,>= 30,متزوج,سليم,>= 02,1,6000
82193,بنك التنمية الإجتماعية فرع الدوادمي,حر,قرض العمل الحر نقدي,قطاع خاص,44000.0,>= 1000,2022-05,ذكر,>= 30,متزوج,سليم,غير معروف,0,0
82194,بنك التنمية الإجتماعية فرع تبوك,حر,قرض العمل الحر نقدي,قطاع حكومي,20000.0,< 1000,2022-06,ذكر,>= 30,مطلق,سليم,غير معروف,0,0
82195,بنك التنمية الإجتماعية فرع جازان,إجتماعي,قرض أسرة,قطاع حكومي,60000.0,>= 1000,2022-06,ذكر,>= 40,متزوج,سليم,>= 02,1,6000

In [33]:
print (data.isnull().sum())

المدينة                0
التصنيف                0
االمنتج                0
قطاع_العميل            0
مبلغ_التمويل           0
قيمة_القسط           196
تاريخ_الصرف            0
جنس_العميل             0
عمر_العميل             0
ألحاله_الإجتماعية    106
إحتياجات_خاصة          0
عدد_أفراد_الأسره       0
زود_الإدخاري           0
القيمة                 0
dtype: int64

In [51]:
data.isnull().sum(axis=0)

المدينة                0
التصنيف                0
االمنتج                0
قطاع_العميل            0
مبلغ_التمويل           0
قيمة_القسط           196
تاريخ_الصرف            0
جنس_العميل             0
عمر_العميل             0
ألحاله_الإجتماعية    106
إحتياجات_خاصة          0
عدد_أفراد_الأسره       0
زود_الإدخاري           0
القيمة                 0
dtype: int64

In [52]:
data.shape

(82196, 14)

In [53]:
(data.isnull().sum(axis = 0) / data.shape[0]) * 100

المدينة              0.000000
التصنيف              0.000000
االمنتج              0.000000
قطاع_العميل          0.000000
مبلغ_التمويل         0.000000
قيمة_القسط           0.238454
تاريخ_الصرف          0.000000
جنس_العميل           0.000000
عمر_العميل           0.000000
ألحاله_الإجتماعية    0.128960
إحتياجات_خاصة        0.000000
عدد_أفراد_الأسره     0.000000
زود_الإدخاري         0.000000
القيمة               0.000000
dtype: float64

In [62]:
data.dropna()

,المدينة,التصنيف,االمنتج,قطاع_العميل,مبلغ_التمويل,قيمة_القسط,تاريخ_الصرف,جنس_العميل,عمر_العميل,ألحاله_الإجتماعية,إحتياجات_خاصة,عدد_أفراد_الأسره,زود_الإدخاري,القيمة
0,بنك التنمية الإجتماعية بالإحساء,نقل,قرض سيارة أجرة,قطاع خاص,78334.0,>= 1000,2022-06,ذكر,>= 40,متزوج,سليم,غير معروف,0,0
1,بنك التنمية الإجتماعية فرع المجمعة,مشروع,قرض التميز,قطاع خاص,2877000.0,>= 1000,2022-03,انثى,>= 30,متزوج,سليم,< 02,0,0
2,بنك التنمية الإجتماعية فرع الرياض,مشروع,قرض مشروع حل,قطاع خاص,281000.0,>= 1000,2022-03,انثى,>= 30,متزوج,سليم,< 02,0,0
3,بنك التنمية الإجتماعية فرع الرياض,مشروع,قرض التميز,قطاع خاص,1700000.0,>= 1000,2022-04,ذكر,>= 40,متزوج,سليم,< 02,0,0
4,بنك التنمية الإجتماعية فرع جدة,مشروع,قرض التميز,قطاع خاص,2218980.0,>= 1000,2022-01,ذكر,>= 30,متزوج,سليم,< 02,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82191,بنك التنمية الإجتماعية فرع حفر الباطن,إجتماعي,قرض زواج,قطاع خاص,42000.0,< 1000,2022-06,ذكر,< 30,متزوج,نعم,>= 02,0,0
82192,بنك التنمية الإجتماعية فرع نجران,إجتماعي,قرض أسرة,قطاع حكومي,60000.0,>= 1000,2022-06,ذكر,>= 30,متزوج,سليم,>= 02,1,6000
82193,بنك التنمية الإجتماعية فرع الدوادمي,حر,قرض العمل الحر نقدي,قطاع خاص,44000.0,>= 1000,2022-05,ذكر,>= 30,متزوج,سليم,غير معروف,0,0
82194,بنك التنمية الإجتماعية فرع تبوك,حر,قرض العمل الحر نقدي,قطاع حكومي,20000.0,< 1000,2022-06,ذكر,>= 30,مطلق,سليم,غير معروف,0,0
82195,بنك التنمية الإجتماعية فرع جازان,إجتماعي,قرض أسرة,قطاع حكومي,60000.0,>= 1000,2022-06,ذكر,>= 40,متزوج,سليم,>= 02,1,6000

In [69]:
data

,المدينة,التصنيف,االمنتج,قطاع_العميل,مبلغ_التمويل,قيمة_القسط,تاريخ_الصرف,جنس_العميل,عمر_العميل,ألحاله_الإجتماعية,إحتياجات_خاصة,عدد_أفراد_الأسره,زود_الإدخاري,القيمة
0,بنك التنمية الإجتماعية بالإحساء,نقل,قرض سيارة أجرة,قطاع خاص,78334.0,>= 1000,2022-06,ذكر,>= 40,متزوج,سليم,غير معروف,0,0
1,بنك التنمية الإجتماعية فرع المجمعة,مشروع,قرض التميز,قطاع خاص,2877000.0,>= 1000,2022-03,انثى,>= 30,متزوج,سليم,< 02,0,0
2,بنك التنمية الإجتماعية فرع الرياض,مشروع,قرض مشروع حل,قطاع خاص,281000.0,>= 1000,2022-03,انثى,>= 30,متزوج,سليم,< 02,0,0
3,بنك التنمية الإجتماعية فرع الرياض,مشروع,قرض التميز,قطاع خاص,1700000.0,>= 1000,2022-04,ذكر,>= 40,متزوج,سليم,< 02,0,0
4,بنك التنمية الإجتماعية فرع جدة,مشروع,قرض التميز,قطاع خاص,2218980.0,>= 1000,2022-01,ذكر,>= 30,متزوج,سليم,< 02,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82191,بنك التنمية الإجتماعية فرع حفر الباطن,إجتماعي,قرض زواج,قطاع خاص,42000.0,< 1000,2022-06,ذكر,< 30,متزوج,نعم,>= 02,0,0
82192,بنك التنمية الإجتماعية فرع نجران,إجتماعي,قرض أسرة,قطاع حكومي,60000.0,>= 1000,2022-06,ذكر,>= 30,متزوج,سليم,>= 02,1,6000
82193,بنك التنمية الإجتماعية فرع الدوادمي,حر,قرض العمل الحر نقدي,قطاع خاص,44000.0,>= 1000,2022-05,ذكر,>= 30,متزوج,سليم,غير معروف,0,0
82194,بنك التنمية الإجتماعية فرع تبوك,حر,قرض العمل الحر نقدي,قطاع حكومي,20000.0,< 1000,2022-06,ذكر,>= 30,مطلق,سليم,غير معروف,0,0
82195,بنك التنمية الإجتماعية فرع جازان,إجتماعي,قرض أسرة,قطاع حكومي,60000.0,>= 1000,2022-06,ذكر,>= 40,متزوج,سليم,>= 02,1,6000

In [81]:
#drop(labels, axis, index, columns, level, inplace, errors)
data.drop(labels=['مبلغ_التمويل'] ,axis=1)

,المدينة,التصنيف,االمنتج,قطاع_العميل,قيمة_القسط,تاريخ_الصرف,جنس_العميل,عمر_العميل,ألحاله_الإجتماعية,إحتياجات_خاصة,عدد_أفراد_الأسره,زود_الإدخاري,القيمة
0,بنك التنمية الإجتماعية بالإحساء,نقل,قرض سيارة أجرة,قطاع خاص,>= 1000,2022-06,ذكر,>= 40,متزوج,سليم,غير معروف,0,0
1,بنك التنمية الإجتماعية فرع المجمعة,مشروع,قرض التميز,قطاع خاص,>= 1000,2022-03,انثى,>= 30,متزوج,سليم,< 02,0,0
2,بنك التنمية الإجتماعية فرع الرياض,مشروع,قرض مشروع حل,قطاع خاص,>= 1000,2022-03,انثى,>= 30,متزوج,سليم,< 02,0,0
3,بنك التنمية الإجتماعية فرع الرياض,مشروع,قرض التميز,قطاع خاص,>= 1000,2022-04,ذكر,>= 40,متزوج,سليم,< 02,0,0
4,بنك التنمية الإجتماعية فرع جدة,مشروع,قرض التميز,قطاع خاص,>= 1000,2022-01,ذكر,>= 30,متزوج,سليم,< 02,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
82191,بنك التنمية الإجتماعية فرع حفر الباطن,إجتماعي,قرض زواج,قطاع خاص,< 1000,2022-06,ذكر,< 30,متزوج,نعم,>= 02,0,0
82192,بنك التنمية الإجتماعية فرع نجران,إجتماعي,قرض أسرة,قطاع حكومي,>= 1000,2022-06,ذكر,>= 30,متزوج,سليم,>= 02,1,6000
82193,بنك التنمية الإجتماعية فرع الدوادمي,حر,قرض العمل الحر نقدي,قطاع خاص,>= 1000,2022-05,ذكر,>= 30,متزوج,سليم,غير معروف,0,0
82194,بنك التنمية الإجتماعية فرع تبوك,حر,قرض العمل الحر نقدي,قطاع حكومي,< 1000,2022-06,ذكر,>= 30,مطلق,سليم,غير معروف,0,0
82195,بنك التنمية الإجتماعية فرع جازان,إجتماعي,قرض أسرة,قطاع حكومي,>= 1000,2022-06,ذكر,>= 40,متزوج,سليم,>= 02,1,6000